# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - 'neon_iris/version.py'

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets: inherit
    with:
      version_file: "neon_iris/version.py"
      setup_py: "setup.py"
      publish_prerelease: false
      publish_pypi: false
  build_and_publish_docker:
    needs: publish_alpha_release
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@FEAT_BetterDockerSupport
    secrets: inherit
    with:
      build_args: "['EXTRAS=gradio']"
      extra_tag: "websat"
      extra_build_args: "['EXTRAS=websat']"