# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'neon_iris/version.py'

jobs:
  build_and_publish_pypi:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@FEAT_SharedScripts
    secrets: inherit
    with:
      version_file: "neon_iris/version.py"
